name: guul_side
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  flutter_svg: ^2.0.17
  fl_chart: ^0.70.2
  shared_preferences: ^2.4.0
  http: ^1.3.0  # Updated to the latest version
  image_picker: ^1.0.7
  connectivity_plus: ^6.1.2
  sqflite: ^2.0.0+4
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

 
 